export const GET_CONGRESSMAN_DETAILS = 'GET_CONGRESSMAN_DETAILS';
export const GET_CONGRESSMAN_DETAILS_FAIL = 'GET_CONGRESSMAN_DETAILS_FAIL';
export const GET_CONGRESSMAN_DETAILS_SUCCESS = 'GET_CONGRESSMAN_DETAILS_SUCCESS';
