/* eslint-disable */
const members = [
  {
     "id": "A000360",
     "title": "Senator, 2nd Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/A000360.json",
     "first_name": "Lamar",
     "middle_name": null,
     "last_name": "Alexander",
     "suffix": null,
     "date_of_birth": "1940-07-03",
     "gender": "M",
     "party": "R",
     "leadership_role": null,
     "twitter_account": "SenAlexander",
     "facebook_account": "senatorlamaralexander",
     "youtube_account": "lamaralexander",
     "govtrack_id": "300002",
     "cspan_id": "5",
     "votesmart_id": "15691",
     "icpsr_id": "40304",
     "crp_id": "N00009888",
     "google_entity_id": "/m/01rbs3",
     "fec_candidate_id": "S2TN00058",
     "url": "https://www.alexander.senate.gov/public",
     "rss_url": "https://www.alexander.senate.gov/public/?a=RSS.Feed",
     "contact_form": "http://www.alexander.senate.gov/public/index.cfm?p=Email",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": 0.324,
     "ideal_point": null,
     "seniority": "17",
     "next_election": "2020",
     "total_votes": 374,
     "missed_votes": 75,
     "total_present": 0,
     "last_updated": "2019-12-04 07:18:43 -0500",
     "ocd_id": "ocd-division/country:us/state:tn",
     "office": "455 Dirksen Senate Office Building",
     "phone": "202-224-4944",
     "fax": "202-228-3398",
     "state": "TN",
     "senate_class": "2",
     "state_rank": "senior",
     "lis_id": "S289"
     ,"missed_votes_pct": 20.05,
     "votes_with_party_pct": 96.98,
     "votes_against_party_pct": 3.02
   },
               {
     "id": "B001230",
     "title": "Senator, 1st Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/B001230.json",
     "first_name": "Tammy",
     "middle_name": null,
     "last_name": "Baldwin",
     "suffix": null,
     "date_of_birth": "1962-02-11",
     "gender": "F",
     "party": "D",
     "leadership_role": null,
     "twitter_account": "SenatorBaldwin",
     "facebook_account": "senatortammybaldwin",
     "youtube_account": "witammybaldwin",
     "govtrack_id": "400013",
     "cspan_id": "57884",
     "votesmart_id": "3470",
     "icpsr_id": "29940",
     "crp_id": "N00004367",
     "google_entity_id": "/m/024v02",
     "fec_candidate_id": "H8WI00018",
     "url": "https://www.baldwin.senate.gov",
     "rss_url": "https://www.baldwin.senate.gov/rss/feeds/?type=all",
     "contact_form": "https://www.baldwin.senate.gov/feedback",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": -0.505,
     "ideal_point": null,
     "seniority": "7",
     "next_election": "2024",
     "total_votes": 374,
     "missed_votes": 1,
     "total_present": 1,
     "last_updated": "2019-12-04 07:19:34 -0500",
     "ocd_id": "ocd-division/country:us/state:wi",
     "office": "709 Hart Senate Office Building",
     "phone": "202-224-5653",
     "fax": null,
     "state": "WI",
     "senate_class": "1",
     "state_rank": "junior",
     "lis_id": "S354"
     ,"missed_votes_pct": 0.27,
     "votes_with_party_pct": 93.66,
     "votes_against_party_pct": 6.34
   },
               {
     "id": "B001261",
     "title": "Senator, 1st Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/B001261.json",
     "first_name": "John",
     "middle_name": null,
     "last_name": "Barrasso",
     "suffix": null,
     "date_of_birth": "1952-07-21",
     "gender": "M",
     "party": "R",
     "leadership_role": "Senate Republican Conference Chair",
     "twitter_account": "SenJohnBarrasso",
     "facebook_account": "johnbarrasso",
     "youtube_account": "barrassowyo",
     "govtrack_id": "412251",
     "cspan_id": "1024777",
     "votesmart_id": "52662",
     "icpsr_id": "40707",
     "crp_id": "N00006236",
     "google_entity_id": "/m/02rsm32",
     "fec_candidate_id": "S6WY00068",
     "url": "https://www.barrasso.senate.gov",
     "rss_url": "https://www.barrasso.senate.gov/public/?a=rss.feed",
     "contact_form": "https://www.barrasso.senate.gov/public/index.cfm/contact-form",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": 0.538,
     "ideal_point": null,
     "seniority": "13",
     "next_election": "2024",
     "total_votes": 374,
     "missed_votes": 0,
     "total_present": 0,
     "last_updated": "2019-12-03 19:50:32 -0500",
     "ocd_id": "ocd-division/country:us/state:wy",
     "office": "307 Dirksen Senate Office Building",
     "phone": "202-224-6441",
     "fax": null,
     "state": "WY",
     "senate_class": "1",
     "state_rank": "junior",
     "lis_id": "S317"
     ,"missed_votes_pct": 0.00,
     "votes_with_party_pct": 96.77,
     "votes_against_party_pct": 3.23
   },
               {
     "id": "B001267",
     "title": "Senator, 3rd Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/B001267.json",
     "first_name": "Michael",
     "middle_name": null,
     "last_name": "Bennet",
     "suffix": null,
     "date_of_birth": "1964-11-28",
     "gender": "M",
     "party": "D",
     "leadership_role": null,
     "twitter_account": "SenBennetCo",
     "facebook_account": "senbennetco",
     "youtube_account": "SenatorBennet",
     "govtrack_id": "412330",
     "cspan_id": "1031622",
     "votesmart_id": "110942",
     "icpsr_id": "40910",
     "crp_id": "N00030608",
     "google_entity_id": "/m/05b60qf",
     "fec_candidate_id": "S0CO00211",
     "url": "https://www.bennet.senate.gov/public",
     "rss_url": null,
     "contact_form": "https://www.bennet.senate.gov/public/index.cfm/contact",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": -0.216,
     "ideal_point": null,
     "seniority": "11",
     "next_election": "2022",
     "total_votes": 374,
     "missed_votes": 109,
     "total_present": 1,
     "last_updated": "2019-12-03 19:50:27 -0500",
     "ocd_id": "ocd-division/country:us/state:co",
     "office": "261 Russell Senate Office Building",
     "phone": "202-224-5852",
     "fax": "202-228-5097",
     "state": "CO",
     "senate_class": "3",
     "state_rank": "senior",
     "lis_id": "S330"
     ,"missed_votes_pct": 29.14,
     "votes_with_party_pct": 93.85,
     "votes_against_party_pct": 6.15
   },
               {
     "id": "B001243",
     "title": "Senator, 1st Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/B001243.json",
     "first_name": "Marsha",
     "middle_name": null,
     "last_name": "Blackburn",
     "suffix": null,
     "date_of_birth": "1952-06-06",
     "gender": "F",
     "party": "R",
     "leadership_role": null,
     "twitter_account": "MarshaBlackburn",
     "facebook_account": "marshablackburn",
     "youtube_account": "RepMarshaBlackburn",
     "govtrack_id": "400032",
     "cspan_id": "31226",
     "votesmart_id": "25186",
     "icpsr_id": "20351",
     "crp_id": "N00003105",
     "google_entity_id": "/m/01fnkt",
     "fec_candidate_id": "H2TN06030",
     "url": "https://www.blackburn.senate.gov",
     "rss_url": null,
     "contact_form": "https://www.blackburn.senate.gov/contact_marsha",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": 0.617,
     "ideal_point": null,
     "seniority": "1",
     "next_election": "2024",
     "total_votes": 374,
     "missed_votes": 3,
     "total_present": 0,
     "last_updated": "2019-12-04 07:19:37 -0500",
     "ocd_id": "ocd-division/country:us/state:tn",
     "office": "357 Dirksen Senate Office Building",
     "phone": "202-224-3344",
     "fax": null,
     "state": "TN",
     "senate_class": "1",
     "state_rank": "junior",
     "lis_id": "S396"
     ,"missed_votes_pct": 0.80,
     "votes_with_party_pct": 92.68,
     "votes_against_party_pct": 7.32
   },
               {
     "id": "B001277",
     "title": "Senator, 3rd Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/B001277.json",
     "first_name": "Richard",
     "middle_name": null,
     "last_name": "Blumenthal",
     "suffix": null,
     "date_of_birth": "1946-02-13",
     "gender": "M",
     "party": "D",
     "leadership_role": null,
     "twitter_account": "SenBlumenthal",
     "facebook_account": "SenBlumenthal",
     "youtube_account": "SenatorBlumenthal",
     "govtrack_id": "412490",
     "cspan_id": "21799",
     "votesmart_id": "1568",
     "icpsr_id": "41101",
     "crp_id": "N00031685",
     "google_entity_id": "/m/03tg8m",
     "fec_candidate_id": "S0CT00177",
     "url": "https://www.blumenthal.senate.gov",
     "rss_url": "https://www.blumenthal.senate.gov/rss/feeds/?type=press",
     "contact_form": "https://www.blumenthal.senate.gov/contact/",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": -0.43,
     "ideal_point": null,
     "seniority": "9",
     "next_election": "2022",
     "total_votes": 374,
     "missed_votes": 4,
     "total_present": 1,
     "last_updated": "2019-12-04 07:19:35 -0500",
     "ocd_id": "ocd-division/country:us/state:ct",
     "office": "706 Hart Senate Office Building",
     "phone": "202-224-2823",
     "fax": "202-224-9673",
     "state": "CT",
     "senate_class": "3",
     "state_rank": "senior",
     "lis_id": "S341"
     ,"missed_votes_pct": 1.07,
     "votes_with_party_pct": 90.56,
     "votes_against_party_pct": 9.44
   },
               {
     "id": "B000575",
     "title": "Senator, 3rd Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/B000575.json",
     "first_name": "Roy",
     "middle_name": null,
     "last_name": "Blunt",
     "suffix": null,
     "date_of_birth": "1950-01-10",
     "gender": "M",
     "party": "R",
     "leadership_role": "Senate Republican Policy Committee Chair",
     "twitter_account": "RoyBlunt",
     "facebook_account": "SenatorBlunt",
     "youtube_account": "SenatorBlunt",
     "govtrack_id": "400034",
     "cspan_id": "45465",
     "votesmart_id": "418",
     "icpsr_id": "29735",
     "crp_id": "N00005195",
     "google_entity_id": "/m/034fn4",
     "fec_candidate_id": "S0MO00183",
     "url": "https://www.blunt.senate.gov",
     "rss_url": null,
     "contact_form": "https://www.blunt.senate.gov/public/index.cfm/contact-roy",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": 0.428,
     "ideal_point": null,
     "seniority": "9",
     "next_election": "2022",
     "total_votes": 374,
     "missed_votes": 4,
     "total_present": 0,
     "last_updated": "2019-12-04 07:19:34 -0500",
     "ocd_id": "ocd-division/country:us/state:mo",
     "office": "260 Russell Senate Office Building",
     "phone": "202-224-5721",
     "fax": "202-224-8149",
     "state": "MO",
     "senate_class": "3",
     "state_rank": "senior",
     "lis_id": "S342"
     ,"missed_votes_pct": 1.07,
     "votes_with_party_pct": 98.37,
     "votes_against_party_pct": 1.63
   },
               {
     "id": "B001288",
     "title": "Senator, 2nd Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/B001288.json",
     "first_name": "Cory",
     "middle_name": null,
     "last_name": "Booker",
     "suffix": null,
     "date_of_birth": "1969-04-27",
     "gender": "M",
     "party": "D",
     "leadership_role": null,
     "twitter_account": "SenBooker",
     "facebook_account": null,
     "youtube_account": "SenCoryBooker",
     "govtrack_id": "412598",
     "cspan_id": "84679",
     "votesmart_id": "76151",
     "icpsr_id": "41308",
     "crp_id": "N00035267",
     "google_entity_id": "/m/06p430",
     "fec_candidate_id": "S4NJ00185",
     "url": "https://www.booker.senate.gov",
     "rss_url": "https://www.booker.senate.gov/rss/",
     "contact_form": "https://www.booker.senate.gov/?p=contact",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": -0.609,
     "ideal_point": null,
     "seniority": "7",
     "next_election": "2020",
     "total_votes": 374,
     "missed_votes": 223,
     "total_present": 1,
     "last_updated": "2019-12-04 07:19:36 -0500",
     "ocd_id": "ocd-division/country:us/state:nj",
     "office": "717 Hart Senate Office Building",
     "phone": "202-224-3224",
     "fax": "202-224-8378",
     "state": "NJ",
     "senate_class": "2",
     "state_rank": "junior",
     "lis_id": "S370"
     ,"missed_votes_pct": 59.63,
     "votes_with_party_pct": 80.54,
     "votes_against_party_pct": 19.46
   },
               {
     "id": "B001236",
     "title": "Senator, 3rd Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/B001236.json",
     "first_name": "John",
     "middle_name": null,
     "last_name": "Boozman",
     "suffix": null,
     "date_of_birth": "1950-12-10",
     "gender": "M",
     "party": "R",
     "leadership_role": null,
     "twitter_account": "JohnBoozman",
     "facebook_account": "JohnBoozman",
     "youtube_account": "BoozmanPressOffice",
     "govtrack_id": "400040",
     "cspan_id": "92069",
     "votesmart_id": "27958",
     "icpsr_id": "20101",
     "crp_id": "N00013873",
     "google_entity_id": "/m/024s3v",
     "fec_candidate_id": "H2AR03176",
     "url": "https://www.boozman.senate.gov/public",
     "rss_url": "https://www.boozman.senate.gov/public/?a=RSS.Feed",
     "contact_form": "https://www.boozman.senate.gov/public/index.cfm/contact",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": 0.4,
     "ideal_point": null,
     "seniority": "9",
     "next_election": "2022",
     "total_votes": 374,
     "missed_votes": 0,
     "total_present": 0,
     "last_updated": "2019-12-03 19:50:35 -0500",
     "ocd_id": "ocd-division/country:us/state:ar",
     "office": "141 Hart Senate Office Building",
     "phone": "202-224-4843",
     "fax": "202-228-1371",
     "state": "AR",
     "senate_class": "3",
     "state_rank": "senior",
     "lis_id": "S343"
     ,"missed_votes_pct": 0.00,
     "votes_with_party_pct": 98.12,
     "votes_against_party_pct": 1.88
   },
               {
     "id": "B001310",
     "title": "Senator, 1st Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/B001310.json",
     "first_name": "Mike",
     "middle_name": null,
     "last_name": "Braun",
     "suffix": null,
     "date_of_birth": "1954-03-24",
     "gender": "M",
     "party": "R",
     "leadership_role": null,
     "twitter_account": "SenatorBraun",
     "facebook_account": null,
     "youtube_account": null,
     "govtrack_id": "412839",
     "cspan_id": null,
     "votesmart_id": "148564",
     "icpsr_id": null,
     "crp_id": "N00041731",
     "google_entity_id": "/g/11f2ckdwty",
     "fec_candidate_id": "S8IN00171",
     "url": "https://www.braun.senate.gov",
     "rss_url": null,
     "contact_form": "http://www.braun.senate.gov/contact-mike",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": null,
     "ideal_point": null,
     "seniority": "1",
     "next_election": "2024",
     "total_votes": 374,
     "missed_votes": 2,
     "total_present": 0,
     "last_updated": "2019-12-03 19:50:28 -0500",
     "ocd_id": "ocd-division/country:us/state:in",
     "office": "374 Russell Senate Office Building",
     "phone": "202-224-4814",
     "fax": null,
     "state": "IN",
     "senate_class": "1",
     "state_rank": "junior",
     "lis_id": "S397"
     ,"missed_votes_pct": 0.53,
     "votes_with_party_pct": 93.78,
     "votes_against_party_pct": 6.22
   },
               {
     "id": "B000944",
     "title": "Senator, 1st Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/B000944.json",
     "first_name": "Sherrod",
     "middle_name": null,
     "last_name": "Brown",
     "suffix": null,
     "date_of_birth": "1952-11-09",
     "gender": "M",
     "party": "D",
     "leadership_role": null,
     "twitter_account": "SenSherrodBrown",
     "facebook_account": "SenatorSherrodBrown",
     "youtube_account": "SherrodBrownOhio",
     "govtrack_id": "400050",
     "cspan_id": "5051",
     "votesmart_id": "27018",
     "icpsr_id": "29389",
     "crp_id": "N00003535",
     "google_entity_id": "/m/034s80",
     "fec_candidate_id": "H2OH13033",
     "url": "https://www.brown.senate.gov",
     "rss_url": "https://www.brown.senate.gov/rss/feeds/?type=all&",
     "contact_form": "http://www.brown.senate.gov/contact/",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": -0.433,
     "ideal_point": null,
     "seniority": "13",
     "next_election": "2024",
     "total_votes": 374,
     "missed_votes": 3,
     "total_present": 1,
     "last_updated": "2019-12-04 07:19:29 -0500",
     "ocd_id": "ocd-division/country:us/state:oh",
     "office": "503 Hart Senate Office Building",
     "phone": "202-224-2315",
     "fax": null,
     "state": "OH",
     "senate_class": "1",
     "state_rank": "senior",
     "lis_id": "S307"
     ,"missed_votes_pct": 0.80,
     "votes_with_party_pct": 92.24,
     "votes_against_party_pct": 7.76
   },
               {
     "id": "B001135",
     "title": "Senator, 3rd Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/B001135.json",
     "first_name": "Richard",
     "middle_name": "M.",
     "last_name": "Burr",
     "suffix": null,
     "date_of_birth": "1955-11-30",
     "gender": "M",
     "party": "R",
     "leadership_role": null,
     "twitter_account": "SenatorBurr",
     "facebook_account": "SenatorRichardBurr",
     "youtube_account": "SenatorRichardBurr",
     "govtrack_id": "400054",
     "cspan_id": "31054",
     "votesmart_id": "21787",
     "icpsr_id": "29548",
     "crp_id": "N00002221",
     "google_entity_id": "/m/03g_s9",
     "fec_candidate_id": "S4NC00089",
     "url": "https://www.burr.senate.gov",
     "rss_url": null,
     "contact_form": "https://www.burr.senate.gov/contact/email",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": 0.451,
     "ideal_point": null,
     "seniority": "15",
     "next_election": "2022",
     "total_votes": 374,
     "missed_votes": 31,
     "total_present": 0,
     "last_updated": "2019-12-03 19:50:37 -0500",
     "ocd_id": "ocd-division/country:us/state:nc",
     "office": "217 Russell Senate Office Building",
     "phone": "202-224-3154",
     "fax": "202-228-2981",
     "state": "NC",
     "senate_class": "3",
     "state_rank": "senior",
     "lis_id": "S300"
     ,"missed_votes_pct": 8.29,
     "votes_with_party_pct": 98.83,
     "votes_against_party_pct": 1.17
   },
               {
     "id": "C000127",
     "title": "Senator, 1st Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/C000127.json",
     "first_name": "Maria",
     "middle_name": null,
     "last_name": "Cantwell",
     "suffix": null,
     "date_of_birth": "1958-10-13",
     "gender": "F",
     "party": "D",
     "leadership_role": null,
     "twitter_account": "SenatorCantwell",
     "facebook_account": "senatorcantwell",
     "youtube_account": "SenatorCantwell",
     "govtrack_id": "300018",
     "cspan_id": "26137",
     "votesmart_id": "27122",
     "icpsr_id": "39310",
     "crp_id": "N00007836",
     "google_entity_id": "/m/01x68t",
     "fec_candidate_id": "S8WA00194",
     "url": "https://www.cantwell.senate.gov",
     "rss_url": null,
     "contact_form": "http://www.cantwell.senate.gov/public/index.cfm/email-maria",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": -0.296,
     "ideal_point": null,
     "seniority": "19",
     "next_election": "2024",
     "total_votes": 374,
     "missed_votes": 2,
     "total_present": 1,
     "last_updated": "2019-12-04 07:19:29 -0500",
     "ocd_id": "ocd-division/country:us/state:wa",
     "office": "511 Hart Senate Office Building",
     "phone": "202-224-3441",
     "fax": null,
     "state": "WA",
     "senate_class": "1",
     "state_rank": "junior",
     "lis_id": "S275"
     ,"missed_votes_pct": 0.53,
     "votes_with_party_pct": 93.11,
     "votes_against_party_pct": 6.89
   },
               {
     "id": "C001047",
     "title": "Senator, 2nd Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/C001047.json",
     "first_name": "Shelley",
     "middle_name": "Moore",
     "last_name": "Capito",
     "suffix": null,
     "date_of_birth": "1953-11-26",
     "gender": "F",
     "party": "R",
     "leadership_role": null,
     "twitter_account": "SenCapito",
     "facebook_account": "senshelley",
     "youtube_account": null,
     "govtrack_id": "400061",
     "cspan_id": "83737",
     "votesmart_id": "11701",
     "icpsr_id": "20146",
     "crp_id": "N00009771",
     "google_entity_id": "/m/024pwq",
     "fec_candidate_id": "H0WV02138",
     "url": "https://www.capito.senate.gov",
     "rss_url": null,
     "contact_form": "https://www.capito.senate.gov/contact/contact-shelley",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": 0.262,
     "ideal_point": null,
     "seniority": "5",
     "next_election": "2020",
     "total_votes": 374,
     "missed_votes": 11,
     "total_present": 0,
     "last_updated": "2019-12-04 07:19:30 -0500",
     "ocd_id": "ocd-division/country:us/state:wv",
     "office": "172 Russell Senate Office Building",
     "phone": "202-224-6472",
     "fax": "202-225-7856",
     "state": "WV",
     "senate_class": "2",
     "state_rank": "junior",
     "lis_id": "S372"
     ,"missed_votes_pct": 2.94,
     "votes_with_party_pct": 98.34,
     "votes_against_party_pct": 1.66
   },
               {
     "id": "C000141",
     "title": "Senator, 1st Class",
     "short_title": "Sen.",
     "api_uri":"https://api.propublica.org/congress/v1/members/C000141.json",
     "first_name": "Benjamin",
     "middle_name": "L.",
     "last_name": "Cardin",
     "suffix": null,
     "date_of_birth": "1943-10-05",
     "gender": "M",
     "party": "D",
     "leadership_role": null,
     "twitter_account": "SenatorCardin",
     "facebook_account": "senatorbencardin",
     "youtube_account": "senatorcardin",
     "govtrack_id": "400064",
     "cspan_id": "4004",
     "votesmart_id": "26888",
     "icpsr_id": "15408",
     "crp_id": "N00001955",
     "google_entity_id": "/m/025k3k",
     "fec_candidate_id": "H6MD03177",
     "url": "https://www.cardin.senate.gov",
     "rss_url": null,
     "contact_form": "http://www.cardin.senate.gov/contact/",
     "in_office": true,
     "cook_pvi": null,
     "dw_nominate": -0.323,
     "ideal_point": null,
     "seniority": "13",
     "next_election": "2024",
     "total_votes": 374,
     "missed_votes": 3,
     "total_present": 1,
     "last_updated": "2019-12-03 19:50:26 -0500",
     "ocd_id": "ocd-division/country:us/state:md",
     "office": "509 Hart Senate Office Building",
     "phone": "202-224-4524",
     "fax": null,
     "state": "MD",
     "senate_class": "1",
     "state_rank": "senior",
     "lis_id": "S308"
     ,"missed_votes_pct": 0.80,
     "votes_with_party_pct": 94.18,
     "votes_against_party_pct": 5.82,
  }
];

export {
  members,
};